name: 🚀 Auto Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    steps:
      - name: 🚀 Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 6m
          script: |
            cd /www/wwwroot/bulikakan.my.id
            git reset --hard HEAD
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan optimize:clear
            
